# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and deploy project to Tomcat server
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build kindergarten-ui
      working-directory: ./kindergarten-ui
      run: npm install && npm run build    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build kindergarten backend
      working-directory: ./kindergarten
      run: sh build.sh
    - name: Deploy kindergarten
      working-directory: ./kindergarten
      run: mvn clean tomcat7:redeploy -Dserver=TomcatServer --no-transfer-progress
